name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
        env:
          STATUS: ${{ job.status }}
      - name: lint
        run: make lint
        env:
          STATUS: ${{ job.status }}
      - name: format
        run: make format
        env:
          STATUS: ${{ job.status }}
      - name: test
        run: make test
        env:
          STATUS: ${{ job.status }}

      - name: Run main script
        run: python src/script_descriptive_stats.py

      - name: List files
        run: |
          pwd
          ls -R

      - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml_pipeline-artifacts
          path: ${{ github.workspace }}/output
      
      - name: Save to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo GH_TOKEN: "${GH_TOKEN}"
          git config --global user.name 'github-actions'
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Add results"
          git push

      - name: Set up status badges
        uses: badgen/badgen-action@v1
        with:
          subject: ${{ github.job }}
          status: ${{ env.STATUS }}
          color: ${{ env.STATUS == 'success' && 'green' || 'red'}}
          label: ${{ github.job }}
          icon: github
